main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('experiences/', views.experiences, name='experiences'),
    path('contact/', views.contact, name='contact'),
    path('story1/', views.story1, name='story1'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

def aboutme(request):
    return render(request, 'aboutme.html')

def hobbies(request):
    return render(request, 'hobbies.html')

def experiences(request):
    return render(request, 'experiences.html')

def contact(request):
    return render(request, 'contact.html')

def story1(request):
    return render(request, 'story1.html')

main/templates/aboutme.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>About Me</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="title">
          <h1>ABOUT ME</h1>
          <p>Hello! I'm Nabila Dita. I'm a technology enthusiast.
            I really love to learn new things and develop my skills.
          </p>
        </div>
      </div>
      <div class="col-sm">
        <div class="biodatacolumn">
          <p><b>Name:</b> Nabila Dita Putri</p>
          <p><b>Date of Birth:</b> May, 5 2001</p>
          <p><b>University:</b> University of Indonesia</p>
          <p><b>Major:</b> Computer Science</p>
          <br>
          <br>
          <p><b>Educational Background</b></p>
          <p>University of Indonesia: 2019 - Now</p>
          <p>SMAN 78 Jakarta: 2016 - 2019</p>
          <p>SMPN 111 Jakarta: 2013 - 2016</p>
          <p>SD BHAKTI YKKP: 2007 - 2013</p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
      crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="{% static 'style.css'%}">
      {% block meta %}
      {% endblock meta %}
</head>


<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <a class="navbar-brand" href="{%url 'main:home'%}"><b>nabila dita</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:home'%}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:aboutme'%}">About Me</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:hobbies'%}">Hobbies</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:experiences'%}">Experiences</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:story1'%}">Story1</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'main:contact'%}">Contact</a>
      </li>
    </ul>
  </div>
</nav>
</body>
{% block content %}
{% endblock content %}
</html>

main/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Contact</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">CONTACT</h1>
<p class="center" id="reachme">reach me through my social media:</p>
<div class="container-fluid" id="iconcontainer">
  <div class="d-inline p-2">
      <a href="https://www.linkedin.com/in/nabiladita"><img src="{% static 'linkedin.png' %}" class="img-fluid" height="70" width="70" /></a>
  </div>
  <div class="d-inline p-2">
    <a href="https://www.instagram.com/nabiladita/"><img src="{% static 'ig.png' %}" class="img-fluid" height="70" width="70" /></a>
  </div>  
  <div class="d-inline p-2">
    <a href="mailto:nabiladitaputri@gmail.com"><img src="{% static 'email.png' %}" class="img-fluid" height="70" width="70" /></a>
  </div>
</div>
{% endblock content %}

main/templates/experiences.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Experiences</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">EXPERIENCES</h1>

      <div class="experiences">
          <p><b>BETIS (Bimbingan Belajar Gratis 2020)</b></p>
          <p>Staff of Academic, Nov 2019-July 2020</p>
          <p>Creating module, exercises, and try-out for participants.
              I also responsible for contacting tutors.
          </p>
          <br>
          <div class="right">
            <p><b>DPM Fasilkom UI</b></p>
            <p>Staff of Administrative, Feb 2020-Now</p>
            <p>Responsible for creating administrative documents (letters,
              reports, etc)
            </p>
            <br>
          </div>
          <p ><b>COMPFEST 12</b></p>
          <p>Staff of Editorial Marketing, Feb 2020-Now</p>
          <p>Writing some articles about technology and press release at Compfest Medium
          </p>
          <a href="https://medium.com/@nabiladita" class="btn btn-sm active" role="button" aria-pressed="true">Let's take a peek on my medium!</a>
      </div>
{% endblock content %}

main/templates/hobbies.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hobbies</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="hobbies">
    <h1>HOBBIES</h1>
  </div>
  <p>One of my hobbies is reading book. Sometimes when you are reading a book,  you just forget anything happen at that moment in real life, you just can live in a new world.</p>
  <p>Here are some of my favorite reading lists:</p>
  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book1.png' %}"target="_blank">
          <img src="{% static 'book1.png' %}" alt="book1" style="width:100%">
        </a>
        <div class="bookname">Holding Up The Universe by Jennifer Niven</div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book2.png' %}" target="_blank">
          <img src="{% static 'book2.png' %}" alt="book2" style="width:100%">
        </a>
        <div class="caption">
          <div class="bookname">All The Bright Places by Jennifer Niven</div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book3.png' %}" target="_blank">
          <img src="{% static 'book3.png' %}" alt="book3" style="width:100%">
        </a>
        <div class="caption">
          <div class="bookname">Eleanor & Park by Rainbow Rowell</div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book4.png' %}" target="_blank">
          <img src="{% static 'book4.png' %}" alt="book4" style="width:100%">
        </a>
        <div class="caption">
          <div class="bookname">Flipped by Wendelin Van Draanen</div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book5.png' %}" target="_blank">
          <img src="{% static 'book5.png' %}" alt="book5" style="width:100%">
        </a>
        <div class="caption">
          <div class="bookname">The Trilogy of Crazy Rich Asians by Kevin Kwan</div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="{% static 'book6.png' %}" target="_blank">
          <img src="{% static 'book6.png' %}" alt="book6" style="width:100%">
        </a>
        <div class="caption">
          <div class="bookname">I Owe You One by Sophie Kinsella</div>
        </div>
      </div>
    </div> 
  </div>
</div>
{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="fotoprofil">
        <img src="{% static 'fotoprofil.png' %}"class="img-fluid" alt="Responsive image">
      </div>
    </div>
    <div class="col-sm">
      <div class="hello">
        <h1>Hello!<br>I'm Nabila.</h1>
      </div>
      <div class="introduction">
        <p>I'm a Computer Science Student.</p>
        <a href="{%url 'main:aboutme'%}" class="btn btn-lg active " role="button" aria-pressed="true">
          <p>Let's find out more about me!</p>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/story1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
<style>
.aboutme {
  background-color: #f1f1f1;
  padding: 30px;
  text-align: center;
}
body {
  background: rgb(197, 226, 230);
  text-align: center;
  font-family: "Muli";
}
table, th, td {
  border-collapse: collapse;
  border: 1px solid black;
}
table.center {
  margin-left:auto; 
  margin-right:auto;
}
.contact {
  background-color: #f1f1f1;
  padding: 5px;
  text-align: center;
}
.icon {
  display:inline-block;
  padding: 25px;
  margin-left:auto; 
  margin-right:auto;
}
</style>
</head>
<body>
  <div class="aboutme">
    <h1>ABOUT ME</h1>
  </div>
  <p>
    <img src="{% static 'Foto profil.jpg' %}" alt="Foto profil" width="200" height="200" allign="middle">    
  </p>
  <p>Hello Everyone!<br>
      My Name is Nabila Dita Putri.<br>
      I'm a computer science student.<br>
      I really love to learn new things, especially about technology.<br>
  </p>
  <h2>Biodata</h2>
  <p>Name: Nabila Dita Putri<br>
    NPM: 1906400085<br>
    University: University of Indonesia<br>
    Class of: 2019<br>
    Hobbies: Drawing, Reading books, Watching movies<br>
  </p>

  <table style="width:50%" class="center">
    <caption><b>Educational Background</b></caption>
      <tr>
        <th>Year</th>
        <th>Education</th>
      </tr>
      <tr>
        <td>2007-2013</td>
        <td>SD Bhakti YKKP</td>
      </tr>
      <tr>
        <td>2013-2016</td>
        <td>SMPN 111 Jakarta</td>
      </tr>
      <tr>
        <td>2016-2019</td>
        <td>SMAN 78 Jakarta</td>
      </tr>
      <tr>
        <td>2019-now</td>
        <td>University of Indonesia</td>
      </tr>
  </table>
  <br>
  <div class="contact">
    <h2>Contact</h2>
      <div class="icon">
        <a href="https://www.linkedin.com/in/nabiladita"><img src="{% static 'linkedin.png' %}" height="50" width="50" /></a>
      </div>
      <div class="icon">
        <a href="https://www.instagram.com/nabiladita/"><img src="{% static 'ig.png' %}" height="50" width="50" /></a>
      </div>  
      <div class="icon">
        <a href="mailto:nabiladitaputri@gmail.com"><img src="{% static 'email.png' %}" height="50" width="50" /></a>
      </div>
  </div>  
</body>
</html>